server:
  port: 9000
spring:
  application:
    name: eurekaServer

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
 
zuul: 
  prefix: /api
  routes:
    EukeraServiceOne:
      path: /EukeraServiceOne/**
      url: http://localhost:9001
    EukeraServiceTwo:
      path: /EukeraServiceTwo/**
      url: http://localhost:9002