server:
  port: 8090
spring:
  application:
    name: eurekaServer

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
 
zuul: 
  prefix: /api
  routes:
    studentservice:
      path: /studentservice/**
      url: http://localhost:8083
    yahooapp:
      path: /yahooapp/**
      url: http://localhost:8082