server:
  port: 9000
spring:
  application:
    name: eureka

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
 
zuul: 
  prefix: /api
  routes:
    EukeraServiceOne:
      path: /ServicePatient/**
      url: http://localhost:9001
    EukeraServiceTwo:
      path: /ServiceDoctor/**
      url: http://localhost:9002
    EukeraServiceThree:
      path: /ServiceAdmin/**
      url: http://localhost:9003
